CONFIG_ROWS = [
    ["clave", "valor", "observacion"],
    ["fuente", "Meta Graph API", "No usar scraping ni password personal"],
    ["modo_inicial", "sample", "Cambiar a collect cuando exista token Meta"],
    ["anonimizacion", "activa_por_defecto", "STORE_AUTHOR_NAME=false"],
]

SHEET_HEADERS = {
    "CONFIGURACION": CONFIG_ROWS[0],
    "EJECUCIONES": [
        "run_id",
        "timestamp_utc",
        "source",
        "status",
        "comments_total",
        "alerts_total",
        "output_files",
        "notes",
    ],
    "COMENTARIOS": [
        "run_id",
        "network",
        "source_account",
        "post_id",
        "post_url",
        "post_created_at",
        "comment_id",
        "comment_created_at",
        "message",
        "author_id_hash",
        "author_name",
        "like_count",
        "reply_count",
        "parent_id",
        "sentiment",
        "sentiment_score",
        "category",
        "urgency",
        "needs_response",
        "matched_keywords",
    ],
    "METRICAS_DIARIAS": [
        "run_id",
        "date",
        "network",
        "source_account",
        "comments_total",
        "positive_total",
        "neutral_total",
        "negative_total",
        "alerts_total",
        "top_categories",
    ],
    "ALERTAS": [
        "run_id",
        "comment_created_at",
        "network",
        "source_account",
        "post_url",
        "comment_id",
        "message",
        "category",
        "urgency",
        "sentiment",
        "matched_keywords",
        "status",
    ],
    "EVIDENCIAS": [
        "run_id",
        "timestamp_utc",
        "artifact_type",
        "file_name",
        "drive_url",
        "local_path",
        "sha256",
        "notes",
    ],
    "ERRORES": [
        "run_id",
        "timestamp_utc",
        "stage",
        "error_type",
        "message",
        "action_required",
    ],
}

